
export const DevSkills = {
  NEXTIQ: [
    'TypeScript',
    'JavaScript',
    'React',
    'Redux',
    'Saga',
    'DynamoDB',
    'Express',
    'Amplify',
    'GraphQL',
    'REST',
    'Cognito',
    'Stripe',
    'S3',
    'SQL',
    'Snowflake',
    'MetaBase',
    'Google Analytics',
    'Lucky Orange',
    'Node.js',
    'HTML(5)',
    'CSS(3)',
    'Styled-Components',
    'React-Router',
    'React-confetti',
    'Debounce',
    'Git',
    'GitLab',
    'Jira',
    'Vimeo',
    'Confluence',
    'Figma',
    'Trello',
    'npm',
  ],
  MELODIENT: [
    'JavaScript',
    'React',
    'Express',
    'Node.js',
    'MongoDB',
    'Mongoose',
    'React-Router',
    'HTML(5)',
    'CSS(3)',
    'Spotify API',
    'REST',
    'OAuth2',
    'Spotify web playback',
    'Axios',
    'Git',
    'GitHub',
    'Heroku',
    'Figma',
    'Trello',
    'npm',
  ],
  DEVMOUNTAIN: [
    'JavaScript',
    'React',
    'MongoDB',
    'Mongoose',
    'Express',
    'Node.js',
    'REST',
    'Postman',
    'SQL',
    'Redux',
    'React-Router',
    'HTML(5)',
    'CSS(3)',
    'Spotify API',
    'OAuth2',
    'Axios',
    'CORS',
    'JSON',
    'Git',
    'GitHub',
    'Heroku',
    'Figma',
    'Trello',
    'npm',
  ],
}